Fix #71 - Update to OpenSSL 1.1.1l
brave/tor_build_scripts pull request #72
Opened 2021-09-22 05:24 UTC by jumde

fix #71

2021-09-22 17:47 UTC, wknapik commented on build_linux.sh
>  docker run --name tor-brave -d tor-brave
```shell
docker run --rm --name tor-brave -d tor-brave
```

2021-09-22 17:47 UTC, wknapik commented on build_linux.sh
>  docker run --name tor-brave -d tor-brave
```shell
docker run --rm --name tor-brave -d tor-brave
```

2021-09-22 17:47 UTC, wknapik commented on build_linux.sh
> +docker kill tor-brave
```shell
docker stop -t 15 tor-brave || docker kill tor-brave
```
would probably be better.

If you do `docker run --rm` above, you also won't have to do `docker rm` here.

2021-09-22 17:49 UTC, wknapik commented on build_mingw.sh
> +docker kill tor-brave-mingw
See: comments for build_linux.sh.

2021-09-23 14:42 UTC, wknapik requested changes
Please change the `ENTRYPOINT` in [Dockefile-linux](https://github.com/brave/tor_build_scripts/blob/e370d22018daf5cc76647fb75c619647cb922c08/Dockerfile-linux#L79) and [Dockerfile-mingw](https://github.com/brave/tor_build_scripts/blob/e370d22018daf5cc76647fb75c619647cb922c08/Dockerfile-mingw#L87). Those are still invalid and will fill up the disk on the jenkins node with an infinitely repeating error message (`dash: 1: read: arg count`). Once this is done, this is fine to merge from my pov.

Some remarks for the future:
* You can use `docker create` instead of `docker run` and you won't have to sleep forever in the `ENTRYPOINT`/`CMD`.
* I'd suggest using container IDs instead of setting fixed container names (`docker create` and `docker run -d` print the ID before exiting). This is more flexible (allows for concurrent runs) and avoids naming conflicts. You can label images and containers with `--label` for cleanup purposes.
* I'd also suggest use [hadolint](https://github.com/hadolint/hadolint) to lint dockerfiles.
* Standard Dockerfile stuff - drop root privileges, use proper init, use the exec form in `ENTRYPOINT`/`CMD`, etc. Hadolint would likely point some of these out.

2021-09-23 16:08 UTC, wknapik approved these changes

2021-09-23 17:45 UTC, diracdeltas approved these changes

2021-09-23 17:51 UTC, darkdh approved these changes

2021-09-28 16:01 UTC, merged